### ISSUE TITLE
App takes ages to refresh balance

### ISSUE THREAD

**Issue by Abcmsaj** [johneas10/bankBar#15]
Sent 1p from Monzo and bankBar just didn't refresh at all until I restarted the application - is there a timer on refresh? I waited about 20 mins

**Comment by johneas10** [comment]
Hi Abcmsaj.

At the moment the Monzo API doesn't support notifications for desktop applications, so there is no way of knowing when to refresh. Because of this, I've set a refresh to trigger every hour.
