### ISSUE TITLE
Pot names not being shown correctly

### ISSUE THREAD

**Issue by therealtbutz** [johneas10/bankBar#20]
If you have a pot with an ampersand in it, this is not shown. Eg. I have a "Stocks & Shares" pot for putting money aside for Freetrade etc, but this is shown as "Stocks  Shares"

**Comment by johneas10** [comment]
Hi @therealtbutz 

Good spot!

This is actually expected behaviour in Electron (see https://github.com/electron/electron/issues/9584).
I have made a small workaround though, I'll upload the new build tomorrow morning.

Cheers

**Comment by johneas10** [comment]
Hi @therealtbutz 

Give this a try...

https://github.com/johneas10/bankBar/releases/tag/v0.7.3

**Comment by therealtbutz** [comment]
Works like a dream! Thanks for that 👍
